name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          sudo mkdir -p /root/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | sudo tee /root/.ssh/id_rsa > /dev/null
          sudo chmod 600 /root/.ssh/id_rsa
          sudo ssh-keyscan -H 13.49.41.220 | sudo tee -a /root/.ssh/known_hosts

      - name: Update code on EC2 by pulling from master
        run: |
          sudo ssh -v -i "${{ secrets.SSH_PRIVATE_KEY }}" ubuntu@13.49.41.220 "cd /home/ubuntu/pharmacy-management-fe && git pull origin main"

          
      - name: Install dependencies
        run: npm install
      - name: Restart PM2 server
        run: |
          sudo ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ubuntu@13.49.41.220 "cd /home/ubuntu/pharmacy-management-fe && npm run build"
